---
author: "Satoshi Kato"
title: rule extraction from xgboost model"
date: "`r format(Sys.time(), '%Y/%m/%d')`"
output:
  html_document:
    fig_caption: yes
    pandoc_args:
      - --from
      - markdown+autolink_bare_uris+tex_math_single_backslash-implicit_figures
    keep_md: yes
    toc: yes
  word_document:
    toc: yes
    toc_depth: 3
  pdf_document:
    toc: yes
    toc_depth: 3
editor_options: 
  chunk_output_type: inline
---

```{r setup, include=FALSE}
knitr::opts_knit$set(progress = TRUE, 
                     verbose  = TRUE, 
                     root.dir = ".")

knitr::opts_chunk$set(collapse = FALSE, 
                      comment = "", 
                      message = TRUE, 
                      warning = FALSE, 
                      include = TRUE,
                      echo    = TRUE)

set.seed(1)
```

```{r install.requirements, eval = FALSE}
install.packages("DiagrammeR", dependencies = TRUE)

```

```{r require.packages, message=FALSE}
require(tidyverse)
require(data.table)
require(xgboost)
library(inTrees)
library(xtable)

require(AUC)
require(caret)
require(DALEX)

```

# Preparation (continued)

```{r load.model.and.data}
loaded.obs  <- readRDS("./middle/data_and_model.Rds")

model.xgb   <- loaded.obs$model$xgb 

train.label <- loaded.obs$data$train$label
train.matrix <- loaded.obs$data$train$matrix
train.xgb.DMatrix <- xgb.DMatrix("./middle/train.xgbDMatrix")

test.label  <- loaded.obs$data$test$label
test.matrix <- loaded.obs$data$test$matrix
test.xgb.DMatrix  <- xgb.DMatrix("./middle/test.xgbDMatrix")

```

# View tree model structure

## Parse a boosted tree model text dump into a data.table structure.

```{r}
xgb.model.dt.tree(model = model.xgb) %>% 
  mutate(Feature = str_trunc(Feature, width = 12, side = "right"),
         Quality = round(Quality, 2),
         Cover   = as.integer(Cover)) %>% 
  data.table()

```

## Project all trees on one tree and plot it

```{r}
# install.packages("rsvg", dependencies = TRUE)
# devtools::install_github('rich-iannone/DiagrammeRsvg')
                          
ggp.multi.tree <- xgb.plot.multi.trees(model = model.xgb, render=FALSE)
DiagrammeR::export_graph(ggp.multi.tree, "./output/image.files/020_summarise_xgbTrees.pdf",
                         width=960, height=720)

```

[See pdf file](./output/image.files/020_summarise_xgbTrees.pdf)

# Plot a boosted tree model

## First tree

```{r, fig.height=8, fig.width=8}
ggp.1st.tree <- xgb.plot.tree(model = model.xgb, trees = 0)
DiagrammeR::export_graph(ggp.multi.tree, "./output/image.files/020_xgb_1st_tree.pdf",
                         width=960, height=720)

```

[See pdf file](./output/image.files/020_xgb_1st_tree.pdf)

## Following booster

```{r, fig.height=8, fig.width=8}
ggp.2nd.tree <- xgb.plot.tree(model = model.xgb, trees = 0)
DiagrammeR::export_graph(ggp.multi.tree, "./output/image.files/020_xgb_2nd_tree.pdf",
                         width=960, height=720)

```

[See pdf file](./output/image.files/020_xgb_2nd_tree.pdf)
