---
author: "Satoshi Kato"
title: "rule extraction from xgboost model"
date: "`r format(Sys.time(), '%Y/%m/%d')`"
output:
  html_document:
    fig_caption: yes
    pandoc_args:
      - --from
      - markdown+autolink_bare_uris+tex_math_single_backslash-implicit_figures
    keep_md: yes
    toc: yes
  word_document:
    toc: yes
    toc_depth: 3
  pdf_document:
    toc: yes
    toc_depth: 3
editor_options: 
  chunk_output_type: inline
---

```{r setup, include=FALSE}
knitr::opts_knit$set(progress = TRUE, 
                     verbose  = TRUE, 
                     root.dir = ".")

knitr::opts_chunk$set(collapse = FALSE, 
                      comment = "", 
                      message = TRUE, 
                      warning = FALSE, 
                      include = TRUE,
                      echo    = TRUE)

set.seed(1)
```

```{r install.requirements, eval = FALSE}
install.packages("inTtrees", dependencies = TRUE)
install.packages("kableExtra", dependencies = TRUE)

```

```{r require.packages, message=FALSE}
require(tidyverse)
require(data.table)
require(xgboost)
library(inTrees)
library(xtable)
require(knitr)
require(kableExtra)

```

# Preparation (continued)

```{r load.model.and.data}
loaded.obs  <- readRDS("./middle/data_and_model.Rds")

model.xgb   <- loaded.obs$model$xgb 

train.label  <- loaded.obs$data$train$label
train.matrix <- loaded.obs$data$train$matrix
train.xgb.DMatrix <- xgb.DMatrix("./middle/train.xgbDMatrix")

test.label  <- loaded.obs$data$test$label
test.matrix <- loaded.obs$data$test$matrix
test.xgb.DMatrix  <- xgb.DMatrix("./middle/test.xgbDMatrix")

```

# Extract rules using inTrees
```{r inTrees}
require(inTrees)

```

## Extract rules from of trees

```{r inTrees.extractRules}
treeList <- XGB2List(xgb = model.xgb, X = train.matrix)
ruleExec <- extractRules(treeList = treeList, 
                         X        = train.matrix,
                         ntree    = 20,
                         random   = FALSE, 
                         digits   = 4)
ruleExec <- unique(ruleExec)

```

```{r inTrees.prune.Rule}
# Assign outcomes to a conditions, and measure the rules
ruleMetric <- getRuleMetric(ruleExec = ruleExec,X = train.matrix,target = train.label)

# Prune irrevant variable-value pair from a rule condition
ruleMetric <- pruneRule(rules = ruleMetric, X = train.matrix,target = train.label)
ruleMetric <- unique(ruleMetric)
# ruleMetric %>% str

```

## build a simplified tree ensemble learner (STEL)

```{r buildLearner}
simple.rules    <- buildLearner(ruleMetric = ruleMetric, 
                                # minFreq    = 0.01,
                                X      = train.matrix, 
                                target = train.label)

simple.readable <- presentRules(rules = simple.rules,
                                colN = colnames(train.matrix),
                                digits = 3)

simple.readable %>% 
  data.frame %>% 
  select(pred, condition, everything()) %>%
  kable(format = "html") %>% 
  kable_styling(bootstrap_options = "striped", full_width = FALSE, position = "left")

```

### prediction using simplified rules

```{r}
pred.intrees <- applyLearner(learner = simple.rules, X = test.matrix)
table(prediction = pred.intrees, 
      truth      = test.label) %>% 
  caret::confusionMatrix()

```

## show all extracted

```{r, results="asis"}
ruleMetric  %>%
  presentRules(
    colN = colnames(train.matrix),
    digits = 3) %>% 
  data.frame %>% 
  select(pred, condition, everything()) %>%
  mutate(pred = pred %>%
           as.character() %>%
           as.numeric() %>%
           round(digits = 4)) %>%
  arrange(pred) %>% 
  kable(format = "html") %>% 
  kable_styling(bootstrap_options = "striped", full_width = FALSE, position = "left")
```



